general:
  description: "Settings common to all the targets."
  prefix:
    type: str
    description: Path to store the intermediate and final results. Will be created if it does not exist.
    required: True
    default: my_project
    examples:
      - /absolute_path/to_some/dir
      - local_path/preferably_the_project_name

  tmux:
    type: bool
    description: "If set, ensures that Snakemake won't start unless you use the tmux session manager."
    required: False
    default: False


sample_sheets:
  description: "The sample sheet describes the sequence files to use, their type (ChIP/Input) and which experimental condition they belong to."

  sample_sheet:
    type: file
    description: Main sample sheet.
    required: True
    default: sample_sheet.txt

  external_control_sample_sheet:
    type: file
    description: "A sample sheet of external controls. For example the same ChIP used in a different species.

Can be used to find non-specific binding by aligning these files to the genome used and seeing
which bins get a lot of reads. These are candidates for blacklisting and tested
according to a Poisson model."
    required: False
    default:


genomes_and_annotations:

  description: "Which genomes and annotations to use"

  genome:
    type: str
    description: "Which genome to use. Must be the UCSC name. Mostly used to automatically fetch genome and chromosome sizes."
    required: True
    default: hg38


alignment:
  description: These flags and options are only of interest if your filetype is fastq.

  hisat2_index_prefix:
    type: str
    description: The prefix of the hisat2 genome index. Premade indexes can be found at ftp://ftp.ccb.jhu.edu/pub/infphilo/hisat2/data These indexes are used to align the fastqs to the genome. If the input is not fastq, these files are not used.
    required: False
    default:
    example:
      "/mnt/cargo/genomes/hisat2/hg38/genome"

  hisat2_extra_flags:
    type: str
    description: Additional flags to give to hisat2.
    required: False
    default: "--no-spliced-alignment -k 1 --no-discordant --no-mixed"

  keep_multi_aligning_reads:
    type: str
    description: If this flag is set, multi aligning reads from the alignment are removed (i.e. those with a NH:i field of 1.)
    required: False
    default: True

  adapters:
    type: [str]
    description: A list of adapters to remove from your fastqs.
    required: False
    default: ""
    example:
      - ACGTACGT
      - AAAAAGGG

  min_read_length:
    type: int
    description: The minimum length of your reads after adapter removal.
    required: False
    default: 14


sequencing:

  description: heyo

  fragment_length:
    type: int
    description: "Estimated size of the sequenced fragments."
    required: True
    default: 150

  fastq_quality:
    type: int
    description: "Minimum required fastq quality."
    required: False
    default: 20
    example:
      - 0
      - 20


heatmaps_and_profileplots:

  description: "Settings for heatmaps and profileplots."

  annotation_gff3:
    type: str
    description: "The gzipped gencode annotation file to use. It is used to find the regions to be plotted in heatmaps and profileplots. If the path starts with www/http/ftp it will be downloaded, otherwise the path will be interpreted to be local.

This kind of high-quality annotation only exists for humans and mice. If your genome is any other, the appropriate regions will be downloaded from UCSC refGene for your genome."
    required: False
    default: ""
    example:
      - private/epipp/gencode.v26.annotation.gff3.gz
      - ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_19/gencode.v19.annotation.gff3.gz

  tss_distance_gene:
    type: int
    default: 3000
    description: "The distance to be shown upstream and downstream of any region with 'gene' in the name in the heatmaps and profileplots."

  tss_distance_other:
    type: int
    default: 500
    description: "The distance to be shown upstream and downstream of any region without 'gene' in the name in the heatmaps and profileplots."

  regions:
    type: [file]
    description: "`regions` is a list of the regions to be plotted in the heatmaps and profileplots.

The following regions are valid:
```'CDS', 'exon', # 'five_prime_UTR', 'gene', 'start_codon', 'stop_codon',
'stop_codon_redefined_as_selenocysteine', 'three_prime_UTR', 'transcript',
'internal_exon'```

Using it requires that you either have the configuration variable
`remote_annotation_gff3` or `local_annotation_gff3` defined."
    required: False
    default: ["genes", "exons"]

  custom_regions:
    type: {name: file}
    default:
    description: "`custom_regions` is a map between region names and bed-files used to define the
custom regions.

Custom region files can also be used to draw different lines and colors for
different regions in the same plot. This can be done by adding a seventh column
called deepTools_group to the file. If used, the file must be sorted on the
column deepTools_group."

differential_enrichment:

  description: limma and stuff

  contrasts:
    type: [str]
    description: "Contrasts to test for differential enrichment between groups.
The names used must be the same as the column names in the design_matrix. By default each group in the design matrix is tested against the others in pairs. By default a design matrix with an intercept where each group in the sample sheet is a column in the design matrix. Command used is model.matrix(~0 + groups)."
    required: False
    default:
    examples:
      - WT-KO1
      - WT-KO2

  design_matrix:
    type: file
    description: "The file used to describe the experimental setup."
    required: False
    default:


peak_calling:

  description: peak calling settings

  peak_callers:
    type: [str]
    description: "The peak callers used to find peaks. Valid values are epic and macs2."
    required: False
    default:
      - macs2
      - epic

  epic_gap:
    type: int
    description: "The epic gaps-allowed parameter."
    required: False
    default: 3


  epic_window_size:
    type: int
    description: "The epic window-size parameter."
    required: False
    default: 200


  macs2_broad:
    type: str
    description: "The macs2 --broad parameter."
    required: False
    default: ""


  macs2_extra_flags:
    type: str
    description: "Any other flags you wish to pass to macs2"
    required: False
    default: ""
    example: "--nomodel --extsize 150"


  csaw_window_size:
    type: int
    description: "The window size csaw should use."
    required: False
    default: 200


  csaw_filter:
    type: int
    description: "The minimum required count sum across libraries for a bin to be included in the analysis."
    required: False
    default: 1
