
general:
  description: "Settings common to all the targets."
  prefix:
    type: str
    description: Path to store the intermediate and final results. Will be created if it does not exist.
    required: True
    default: my_project
    examples:
      - /absolute_path/to_some/dir
      - local_path/preferably_the_project_name

  tmux:
    type: bool
    description: "If set, ensures that Snakemake won't start unless you use the tmux session manager."
    required: False
    default: False


sample_sheets:
  description: "The sample sheet describes the sequence files to use, their type (ChIP/Input) and which experimental condition they belong to."

  sample_sheet:
    type: file
    description: Main sample sheet.
    required: True
    default: sample_sheet.txt

  external_control_sample_sheet:
    type: file
    description: "A sample sheet of external controls. For example the same ChIP used in a different species.

Can be used to find non-specific binding by aligning these files to the genome used and seeing
which bins get a lot of reads. These are candidates for blacklisting and tested
according to a Poisson model."
    required: False


genomes_and_annotations:

  description: "Which genomes and annotations to use"

  genome:
    type: str
    description: "Which genome to use. Must be the UCSC name. Mostly used to automatically fetch genome and chromosome sizes."
    required: True
    default: hg38
