"""
Should be able to generate the docs for you.
  - Includes graphs, i.e. must download data and run pipeline
  - Must use docstring to describe each main target
  - Other data must be kept elsewhere
"""

rule all:
    input:
        "docs/{target}.rst".expand(target="pca")

"Have code that collects targets from the main Snakefile first and their comments and their output paths"




rule pca:
    input:
        expand("{prefix}/data/plot_pca/pca_{multibigwig}.pdf", prefix=prefix, multibigwig="chip_vs_merged_input")
    output:
        "docs/pca.rst"
    run:
        main_description = "bincs can create three types of PCA for you."
